### PR TITLE
Add more tools and minor design changes

### PR DESCRIPTION
**Pull request by srish**
@n3rsti Hi! I hope you had a great Google Code-in :)

I've made a few minor changes to the awesome tool you have developed (as I mentioned to you in late December) :) Here they are: 
* Added more tools and modified description of existing ones
* Added a footer
* The footer is sticky (uses a different css class) if there are no tools to show in the search results. And, a message is shown to the user. 
* Overall made some design changes to match it with the Toolforge homepage here http://tools.wmflabs.org/ and make it slightly less bold. 

Here is how it appears for me on a MAC machine in a Chrome browser window:
Screen Shot 2020-02-20 at 1 34 04 AM

Could you review once and if you are happy with the changes merge them? Post that I can work on making them live and then we will be linking it from the Toolforge's homepage :)

Also, I might stop the service for `tools-gallery` & `tool-gallery` as we don't need them now. Hope to hear from you soon!

### CODE REVIEW

**Comment by n3rsti** [comment]
Wow, it looks great!

**Comment by n3rsti** [comment]
Even though I didn't win the GCI, I enjoyed it very much and I can't wait for the next GCI competition.

**Comment by srish** [comment]
@n3rsti thank you for merging :)

**Comment by srish** [comment]
@n3rsti also, could you add me (username `srishakatux`) as a maintainer to `tool-gallery`, `tools-gallery` and `toolforge-gallery` so that I can work on the next steps? Thank you!

**Comment by n3rsti** [comment]
I added you as a maintainer.

**Comment by srish** [comment]
I only have access to one :-/ 
Screen Shot 2020-02-21 at 12 54 43 AM

**Pull request merged**
